mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
server:
  port: 8081

markerhub:
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token有效时长，7天，单位秒
    expire: 604800
    header: token

#DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 88888888
  main:
    allow-bean-definition-overriding: true
shiro-redis:
  enabled: true
  redis-manager:
    host: 47.99.34.106:6379


aliyun:
  oss:
    #oss 对外服务的访问域名
    endpoint: oss-cn-hangzhou.aliyuncs.com
    # 访问身份验证中用到用户标识
    accessKeyId: LTAI5tB5McTpieaGGHmFEw58
    # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    accessKeySecret: i1Lrfwlcu68DUGydhpq3HTFtyyCvxH
    # 存储空间
    bucketName: xiaoli-oss1





